### ISSUE TITLE
Start reimplementing geometry in Cython or Numba

### ISSUE THREAD

**Issue by krzysztofarendt** [krzysztofarendt/building3d#60]
Classes which are computation-intensive, like `Polygon` and `Point` should be rewritten to Cython:
https://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html

**Comment by krzysztofarendt** [comment]
Or Taichi Lang: https://docs.taichi-lang.org/

**Comment by krzysztofarendt** [comment]
Other alternatives:
- numba
- C, ctypes, CUnit
- C++, pybind11

**Comment by Tokarzewski** [comment]
Hi @krzysztofarendt

Did you consider Mojo?
https://www.modular.com/mojo

**Comment by krzysztofarendt** [comment]
Hi @Tokarzewski, yes, but it has some limitations which I don't like for this particular project: https://docs.modular.com/mojo/manual/python/

I want to:
- keep as much code as possible in Python, to make it more accessible to other developers and easier to maintain
- compile to machine code only modules which are critical for the performance (solvers, geometry)
- be able to use these compiled modules from other Python modules (I don't want to rewrite everything)

Currently, you cannot call Mojo from Python, while calling Python from Mojo is possible but limited.

As for the other options:
- numba is the easiest and it is very fast, but it only accepts a subset of Python, so I would have to rewrite a lot of code. I have been using it only with functions. I know it has [some support for classes](https://numba.readthedocs.io/en/stable/user/jitclass.html), but I have not tested it yet. 
- Cython is very mature and can compile most of regular Python code, so I could make changes incrementally. It is easier to learn by Python developers than C/C++.
- C/C++ - if I have to rewrite parts of code to numba-compatible or to Cython, why not rewrite to C/C++ anyway? Easy integration with Python via ctypes, pybind11. On the other hand, it is further away from my goal of having as much as possible of the code in Python. It would also take me more time than both numba and Cython.

**Comment by krzysztofarendt** [comment]
Another factor to take into account (Mojo not included, because it is not open source anyway):
<img width="651" alt="image" src="https://github.com/user-attachments/assets/d3ce4682-d66d-4d50-8329-699c7ae56eca">

**Comment by Tokarzewski** [comment]
@krzysztofarendt thanks for that awesome explanation. It seems to be too early for Mojo.

**Comment by Tokarzewski** [comment]
I could also recommend [topologicpy](https://github.com/wassimj/topologicpy).
It is a py library built on top of the OpenCASCADE C++ core that has 
geometry, topology, graph functionalities and integrations with many other libraries and engines.

**Comment by krzysztofarendt** [comment]
Very interesting project which would be potentially useful in my case, but it is licensed under AGPL3, which as far as I understand would force me to license my project also under AGPL3. I prefer to stay with the MIT license.

**Comment by krzysztofarendt** [comment]
I decided to go with numba: https://github.com/krzysztofarendt/building3d/tree/numba

**Comment by krzysztofarendt** [comment]
Merged.
